from django.db.models import *
from mongoengine import *

print 'in props/models'

#class Properties( Document ):
#    city = StringField(max_length = 30)
#    neighborhood = StringField(max_length = 30)
#    zip = IntField()
#    sqft = IntField()
#    sales = ListField(DictField())
#    longitude = DecimalField()
#    county = StringField(max_length = 30)
#    trulia_link =  StringField(max_length = 100)
#    state = IntField()
#    address = StringField(max_length = 30)
#    latitude = IntField()
#    type = StringField(max_length = 30)
#    parsed_past_sales = IntField()
#    parsing_past_sales = IntField()
#    num_beds  = IntField( default=0 )
#    num_baths = IntField( default=0 )
#    num_park = IntField( default=0 )
#    type      = IntField( default=0 )
#    trulia_id = IntField( default=0 )

print 'in props/models declaring states class'
class States( Document ):
    RegionName = StringField()

    PctTransactionsThatArePreviouslyForeclosuredHomes_AllHomes = ListField()
    UnsoldReos_AllHomes = ListField()
    Zhvi_SingleFamilyResidence = ListField()
    NumberOfHomesForRent_AllHomes = ListField()
    Zhvi_2bedroom = ListField()
    MedianSoldPricePerSqft_Condominum = ListField()
    MedianListingPrice_AllHomes = ListField()
    DaysOnZillow_Public = ListField()
    MedianRentalPricePerSqft_AllHomes = ListField()
    MedianValuePerSqft_AllHomes = ListField()
    Zhvi_4bedroom = ListField()
    MedianSoldPricePerSqft_AllHomes = ListField()
    MedianSoldPrice_AllHomes = ListField()
    Zri_AllHomes = ListField()
    Turnover_AllHomes = ListField()
    PctOfHomesIncreasingInValues_AllHomes = ListField()
    MedianPctOfPriceReduction_AllHomes = ListField()
    MedianListingPricePerSqft_AllHomes = ListField()
    MedianSoldPricePerSqft_SingleFamilyResidence = ListField()
    HomesSoldAsForeclosures_Ratio_AllHomes = ListField()
    Zhvi_5BedroomOrMore = ListField()
    Zhvi_BottomTier = ListField()
    PriceToRentRatio_AllHomes = ListField()
    Zhvi_MiddleTier = ListField()
    Zhvi_Condominum = ListField()
    PctOfListingsWithPriceReductions_AllHomes = ListField()
    SalePriceToListRatio_AllHomes = ListField()
    MedianRentalPrice_AllHomes = ListField()
    Zhvi_1bedroom = ListField()
    Public = ListField()
    ZriPerSqft_AllHomes = ListField()
    Zhvi_AllHomes = ListField()
    Zhvi_3bedroom = ListField()
    Zhvi_TopTier = ListField()
    PctOfHomesDecreasingInValues_AllHomes = ListField()
    #dates
    PctTransactionsThatArePreviouslyForeclosuredHomes_AllHomes_dates = ListField()
    UnsoldReos_AllHomes_dates = ListField()
    Zhvi_SingleFamilyResidence_dates = ListField()
    NumberOfHomesForRent_AllHomes_dates = ListField()
    Zhvi_2bedroom_dates = ListField()
    MedianSoldPricePerSqft_Condominum_dates = ListField()
    MedianListingPrice_AllHomes_dates = ListField()
    DaysOnZillow_Public_dates = ListField()
    MedianRentalPricePerSqft_AllHomes_dates = ListField()
    MedianValuePerSqft_AllHomes_dates = ListField()
    Zhvi_4bedroom_dates = ListField()
    MedianSoldPricePerSqft_AllHomes_dates = ListField()
    MedianSoldPrice_AllHomes_dates = ListField()
    Zri_AllHomes_dates = ListField()
    Turnover_AllHomes_dates = ListField()
    PctOfHomesIncreasingInValues_AllHomes_dates = ListField()
    MedianPctOfPriceReduction_AllHomes_dates = ListField()
    MedianListingPricePerSqft_AllHomes_dates = ListField()
    MedianSoldPricePerSqft_SingleFamilyResidence_dates = ListField()
    HomesSoldAsForeclosures_Ratio_AllHomes_dates = ListField()
    Zhvi_5BedroomOrMore_dates = ListField()
    Zhvi_BottomTier_dates = ListField()
    PriceToRentRatio_AllHomes_dates = ListField()
    Zhvi_MiddleTier_dates = ListField()
    Zhvi_Condominum_dates = ListField()
    PctOfListingsWithPriceReductions_AllHomes_dates = ListField()
    SalePriceToListRatio_AllHomes_dates = ListField()
    MedianRentalPrice_AllHomes_dates = ListField()
    Zhvi_1bedroom_dates = ListField()
    Public_dates = ListField()
    ZriPerSqft_AllHomes_dates = ListField()
    Zhvi_AllHomes_dates = ListField()
    Zhvi_3bedroom_dates = ListField()
    Zhvi_TopTier_dates = ListField()
    PctOfHomesDecreasingInValues_AllHomes_dates = ListField()

print 'in props/models declaring cities class'
class Cities( Document ):
    RegionName = StringField()
    State = StringField()

    MedianPctOfPriceReduction_AllHomes = ListField()
    Zhvi_SingleFamilyResidence = ListField()
    PctOfHomesIncreasingInValues_AllHomes = ListField()
    Zri_AllHomes = ListField()
    Zhvi_MiddleTier = ListField()
    PctTransactionsThatArePreviouslyForeclosuredHomes_AllHomes = ListField()
    Zhvi_2bedroom = ListField()
    Zhvi_1bedroom = ListField()
    Zhvi_4bedroom = ListField()
    Public = ListField()
    Zhvi_AllHomes = ListField()
    Zhvi_5BedroomOrMore = ListField()
    MedianSoldPricePerSqft_AllHomes = ListField()
    MedianSoldPricePerSqft_Condominum = ListField()
    UnsoldReos_AllHomes = ListField()
    MedianValuePerSqft_AllHomes = ListField()
    Zhvi_Condominum = ListField()
    MedianSoldPrice_AllHomes = ListField()
    MedianRentalPricePerSqft_AllHomes = ListField()
    MedianListingPrice_AllHomes = ListField()
    NumberOfHomesForRent_AllHomes = ListField()
    ZriPerSqft_AllHomes = ListField()
    PctOfHomesDecreasingInValues_AllHomes = ListField()
    Zhvi_3bedroom = ListField()
    Zhvi_BottomTier = ListField()
    PriceToRentRatio_AllHomes = ListField()
    MedianRentalPrice_AllHomes = ListField()
    Turnover_AllHomes = ListField()
    SalePriceToListRatio_AllHomes = ListField()
    HomesSoldAsForeclosures_Ratio_AllHomes = ListField()
    PctOfListingsWithPriceReductions_AllHomes = ListField()
    RegionName = ListField()
    MedianSoldPricePerSqft_SingleFamilyResidence = ListField()
    MedianListingPricePerSqft_AllHomes = ListField()
    Zhvi_TopTier = ListField()
    # time series dates
    MedianPctOfPriceReduction_AllHomes_dates = ListField()
    Zhvi_SingleFamilyResidence_dates = ListField()
    PctOfHomesIncreasingInValues_AllHomes_dates = ListField()
    Zri_AllHomes_dates = ListField()
    Zhvi_MiddleTier_dates = ListField()
    PctTransactionsThatArePreviouslyForeclosuredHomes_AllHomes_dates = ListField()
    Zhvi_2bedroom_dates = ListField()
    Zhvi_1bedroom_dates = ListField()
    Zhvi_4bedroom_dates = ListField()
    Public_dates = ListField()
    Zhvi_AllHomes_dates = ListField()
    Zhvi_5BedroomOrMore_dates = ListField()
    MedianSoldPricePerSqft_AllHomes_dates = ListField()
    MedianSoldPricePerSqft_Condominum_dates = ListField()
    UnsoldReos_AllHomes_dates = ListField()
    MedianValuePerSqft_AllHomes_dates = ListField()
    Zhvi_Condominum_dates = ListField()
    MedianSoldPrice_AllHomes_dates = ListField()
    MedianRentalPricePerSqft_AllHomes_dates = ListField()
    MedianListingPrice_AllHomes_dates = ListField()
    NumberOfHomesForRent_AllHomes_dates = ListField()
    ZriPerSqft_AllHomes_dates = ListField()
    PctOfHomesDecreasingInValues_AllHomes_dates = ListField()
    Zhvi_3bedroom_dates = ListField()
    Zhvi_BottomTier_dates = ListField()
    PriceToRentRatio_AllHomes_dates = ListField()
    MedianRentalPrice_AllHomes_dates = ListField()
    Turnover_AllHomes_dates = ListField()
    SalePriceToListRatio_AllHomes_dates = ListField()
    HomesSoldAsForeclosures_Ratio_AllHomes_dates = ListField()
    PctOfListingsWithPriceReductions_AllHomes_dates = ListField()
    RegionName_dates = ListField()
    MedianSoldPricePerSqft_SingleFamilyResidence_dates = ListField()
    MedianListingPricePerSqft_AllHomes_dates = ListField()
    Zhvi_TopTier_dates = ListField()

print 'in props/models declaring counties class'
class Counties( Document ):
    RegionName = StringField()
    State = StringField()
    City = StringField()
    Metro = StringField()

    MedianPctOfPriceReduction_AllHomes = ListField()
    Zhvi_SingleFamilyResidence = ListField()
    DaysOnZillow_Public = ListField()
    PctOfHomesIncreasingInValues_AllHomes = ListField()
    Zri_AllHomes = ListField()
    Zhvi_MiddleTier = ListField()
    PctTransactionsThatArePreviouslyForeclosuredHomes_AllHomes = ListField()
    Zhvi_2bedroom = ListField()
    Zhvi_1bedroom = ListField()
    Zhvi_4bedroom = ListField()
    Public = ListField()
    Zhvi_AllHomes = ListField()
    Zhvi_5BedroomOrMore = ListField()
    MedianSoldPricePerSqft_AllHomes = ListField()
    MedianSoldPricePerSqft_Condominum = ListField()
    UnsoldReos_AllHomes = ListField()
    MedianValuePerSqft_AllHomes = ListField()
    Zhvi_Condominum = ListField()
    MedianSoldPrice_AllHomes = ListField()
    MedianRentalPricePerSqft_AllHomes = ListField()
    MedianListingPrice_AllHomes = ListField()
    NumberOfHomesForRent_AllHomes = ListField()
    ZriPerSqft_AllHomes = ListField()
    PctOfHomesDecreasingInValues_AllHomes = ListField()
    Zhvi_3bedroom = ListField()
    Zhvi_BottomTier = ListField()
    PriceToRentRatio_AllHomes = ListField()
    MedianRentalPrice_AllHomes = ListField()
    Turnover_AllHomes = ListField()
    SalePriceToListRatio_AllHomes = ListField()
    HomesSoldAsForeclosures_Ratio_AllHomes = ListField()
    PctOfListingsWithPriceReductions_AllHomes = ListField()
    MedianSoldPricePerSqft_SingleFamilyResidence = ListField()
    MedianListingPricePerSqft_AllHomes = ListField()
    Zhvi_TopTier = ListField()

    #time series dates
    MedianPctOfPriceReduction_AllHomes_dates = ListField()
    Zhvi_SingleFamilyResidence_dates = ListField()
    DaysOnZillow_Public_dates = ListField()
    PctOfHomesIncreasingInValues_AllHomes_dates = ListField()
    Zri_AllHomes_dates = ListField()
    Zhvi_MiddleTier_dates = ListField()
    PctTransactionsThatArePreviouslyForeclosuredHomes_AllHomes_dates = ListField()
    Zhvi_2bedroom_dates = ListField()
    Zhvi_1bedroom_dates = ListField()
    Zhvi_4bedroom_dates = ListField()
    Public_dates = ListField()
    Zhvi_AllHomes_dates = ListField()
    Zhvi_5BedroomOrMore_dates = ListField()
    MedianSoldPricePerSqft_AllHomes_dates = ListField()
    MedianSoldPricePerSqft_Condominum_dates = ListField()
    UnsoldReos_AllHomes_dates = ListField()
    MedianValuePerSqft_AllHomes_dates = ListField()
    Zhvi_Condominum_dates = ListField()
    MedianSoldPrice_AllHomes_dates = ListField()
    MedianRentalPricePerSqft_AllHomes_dates = ListField()
    MedianListingPrice_AllHomes_dates = ListField()
    NumberOfHomesForRent_AllHomes_dates = ListField()
    ZriPerSqft_AllHomes_dates = ListField()
    PctOfHomesDecreasingInValues_AllHomes_dates = ListField()
    Zhvi_3bedroom_dates = ListField()
    Zhvi_BottomTier_dates = ListField()
    PriceToRentRatio_AllHomes_dates = ListField()
    MedianRentalPrice_AllHomes_dates = ListField()
    Turnover_AllHomes_dates = ListField()
    SalePriceToListRatio_AllHomes_dates = ListField()
    HomesSoldAsForeclosures_Ratio_AllHomes_dates = ListField()
    PctOfListingsWithPriceReductions_AllHomes_dates = ListField()
    MedianSoldPricePerSqft_SingleFamilyResidence_dates = ListField()
    MedianListingPricePerSqft_AllHomes_dates = ListField()
    Zhvi_TopTier_dates = ListField()

print 'in props/models declaring neighborhoods class'
class Neighborhoods( Document ):
    RegionName = StringField()
    State = StringField()
    City = StringField()
    Metro = StringField()

    Zhvi_BottomTier = ListField()
    UnsoldReos_AllHomes = ListField()
    NumberOfHomesForRent_AllHomes = ListField()
    Zhvi_2bedroom = ListField()
    MedianSoldPricePerSqft_Condominum = ListField()
    MedianListingPrice_AllHomes = ListField()
    Zhvi_SingleFamilyResidence = ListField()
    MedianRentalPricePerSqft_AllHomes = ListField()
    MedianValuePerSqft_AllHomes = ListField()
    Zhvi_4bedroom = ListField()
    MedianSoldPrice_AllHomes = ListField()
    Zri_AllHomes = ListField()
    Turnover_AllHomes = ListField()
    PctOfHomesIncreasingInValues_AllHomes = ListField()
    MedianPctOfPriceReduction_AllHomes = ListField()
    MedianListingPricePerSqft_AllHomes = ListField()
    MedianSoldPricePerSqft_SingleFamilyResidence = ListField()
    HomesSoldAsForeclosures_Ratio_AllHomes = ListField()
    Zhvi_5BedroomOrMore = ListField()
    PctTransactionsThatArePreviouslyForeclosuredHomes_AllHomes = ListField()
    PriceToRentRatio_AllHomes = ListField()
    Zhvi_MiddleTier = ListField()
    Zhvi_Condominum = ListField()
    PctOfListingsWithPriceReductions_AllHomes = ListField()
    SalePriceToListRatio_AllHomes = ListField()
    MedianRentalPrice_AllHomes = ListField()
    Zhvi_1bedroom = ListField()
    MedianSoldPricePerSqft_AllHomes = ListField()
    ZriPerSqft_AllHomes = ListField()
    Zhvi_AllHomes = ListField()
    Zhvi_3bedroom = ListField()
    Zhvi_TopTier = ListField()
    PctOfHomesDecreasingInValues_AllHomes = ListField()

    # time series dates
    Zhvi_BottomTier_dates = ListField()
    UnsoldReos_AllHomes_dates = ListField()
    NumberOfHomesForRent_AllHomes_dates = ListField()
    Zhvi_2bedroom_dates = ListField()
    MedianSoldPricePerSqft_Condominum_dates = ListField()
    MedianListingPrice_AllHomes_dates = ListField()
    Zhvi_SingleFamilyResidence_dates = ListField()
    MedianRentalPricePerSqft_AllHomes_dates = ListField()
    MedianValuePerSqft_AllHomes_dates = ListField()
    Zhvi_4bedroom_dates = ListField()
    MedianSoldPrice_AllHomes_dates = ListField()
    Zri_AllHomes_dates = ListField()
    Turnover_AllHomes_dates = ListField()
    PctOfHomesIncreasingInValues_AllHomes_dates = ListField()
    MedianPctOfPriceReduction_AllHomes_dates = ListField()
    MedianListingPricePerSqft_AllHomes_dates = ListField()
    MedianSoldPricePerSqft_SingleFamilyResidence_dates = ListField()
    HomesSoldAsForeclosures_Ratio_AllHomes_dates = ListField()
    Zhvi_5BedroomOrMore_dates = ListField()
    PctTransactionsThatArePreviouslyForeclosuredHomes_AllHomes_dates = ListField()
    PriceToRentRatio_AllHomes_dates = ListField()
    Zhvi_MiddleTier_dates = ListField()
    Zhvi_Condominum_dates = ListField()
    PctOfListingsWithPriceReductions_AllHomes_dates = ListField()
    SalePriceToListRatio_AllHomes_dates = ListField()
    MedianRentalPrice_AllHomes_dates = ListField()
    Zhvi_1bedroom_dates = ListField()
    MedianSoldPricePerSqft_AllHomes_dates = ListField()
    ZriPerSqft_AllHomes_dates = ListField()
    Zhvi_AllHomes_dates = ListField()
    Zhvi_3bedroom_dates = ListField()
    Zhvi_TopTier_dates = ListField()
    PctOfHomesDecreasingInValues_AllHomes_dates = ListField()

print 'in props/models declaring metros class'
class Metros(Document ):
    RegionName = StringField()
    State = StringField()
    City = StringField()

    PctTransactionsThatArePreviouslyForeclosuredHomes_AllHomes = ListField()
    UnsoldReos_AllHomes = ListField()
    Zhvi_SingleFamilyResidence = ListField()
    NumberOfHomesForRent_AllHomes = ListField()
    Zhvi_2bedroom = ListField()
    MedianSoldPricePerSqft_Condominum = ListField()
    MedianListingPrice_AllHomes = ListField()
    DaysOnZillow_Public = ListField()
    MedianRentalPricePerSqft_AllHomes = ListField()
    MedianValuePerSqft_AllHomes = ListField()
    Zhvi_4bedroom = ListField()
    MedianSoldPrice_AllHomes = ListField()
    Zri_AllHomes = ListField()
    Turnover_AllHomes = ListField()
    PctOfHomesIncreasingInValues_AllHomes = ListField()
    MedianPctOfPriceReduction_AllHomes = ListField()
    MedianListingPricePerSqft_AllHomes = ListField()
    MedianSoldPricePerSqft_SingleFamilyResidence = ListField()
    HomesSoldAsForeclosures_Ratio_AllHomes = ListField()
    Zhvi_5BedroomOrMore = ListField()
    Zhvi_BottomTier = ListField()
    PriceToRentRatio_AllHomes = ListField()
    Zhvi_MiddleTier = ListField()
    Zhvi_Condominum = ListField()
    PctOfListingsWithPriceReductions_AllHomes = ListField()
    SalePriceToListRatio_AllHomes = ListField()
    MedianRentalPrice_AllHomes = ListField()
    Zhvi_1bedroom = ListField()
    MedianSoldPricePerSqft_AllHomes = ListField()
    ZriPerSqft_AllHomes = ListField()
    Zhvi_AllHomes = ListField()
    Zhvi_3bedroom = ListField()
    Zhvi_TopTier = ListField()
    PctOfHomesDecreasingInValues_AllHomes = ListField()

    PctTransactionsThatArePreviouslyForeclosuredHomes_AllHomes_dates = ListField()
    UnsoldReos_AllHomes_dates = ListField()
    Zhvi_SingleFamilyResidence_dates = ListField()
    NumberOfHomesForRent_AllHomes_dates = ListField()
    Zhvi_2bedroom_dates = ListField()
    MedianSoldPricePerSqft_Condominum_dates = ListField()
    MedianListingPrice_AllHomes_dates = ListField()
    DaysOnZillow_Public_dates = ListField()
    MedianRentalPricePerSqft_AllHomes_dates = ListField()
    MedianValuePerSqft_AllHomes_dates = ListField()
    Zhvi_4bedroom_dates = ListField()
    MedianSoldPrice_AllHomes_dates = ListField()
    Zri_AllHomes_dates = ListField()
    Turnover_AllHomes_dates = ListField()
    PctOfHomesIncreasingInValues_AllHomes_dates = ListField()
    MedianPctOfPriceReduction_AllHomes_dates = ListField()
    MedianListingPricePerSqft_AllHomes_dates = ListField()
    MedianSoldPricePerSqft_SingleFamilyResidence_dates = ListField()
    HomesSoldAsForeclosures_Ratio_AllHomes_dates = ListField()
    Zhvi_5BedroomOrMore_dates = ListField()
    Zhvi_BottomTier_dates = ListField()
    PriceToRentRatio_AllHomes_dates = ListField()
    Zhvi_MiddleTier_dates = ListField()
    Zhvi_Condominum_dates = ListField()
    PctOfListingsWithPriceReductions_AllHomes_dates = ListField()
    SalePriceToListRatio_AllHomes_dates = ListField()
    MedianRentalPrice_AllHomes_dates = ListField()
    Zhvi_1bedroom_dates = ListField()
    MedianSoldPricePerSqft_AllHomes_dates = ListField()
    ZriPerSqft_AllHomes_dates = ListField()
    Zhvi_AllHomes_dates = ListField()
    Zhvi_3bedroom_dates = ListField()
    Zhvi_TopTier_dates = ListField()
    PctOfHomesDecreasingInValues_AllHomes_dates = ListField()


print 'in props/models declaring zips class'
class Zips( Document ):
    RegionName = StringField()
    State = StringField()
    City = StringField()
    County = StringField()
    Metro = StringField()

    PctTransactionsThatArePreviouslyForeclosuredHomes_AllHomes = ListField()
    UnsoldReos_AllHomes = ListField()
    NumberOfHomesForRent_AllHomes = ListField()
    Zhvi_2bedroom = ListField()
    MedianSoldPricePerSqft_Condominum = ListField()
    MedianListingPrice_AllHomes = ListField()
    Zhvi_SingleFamilyResidence = ListField()
    MedianRentalPricePerSqft_AllHomes = ListField()
    MedianValuePerSqft_AllHomes = ListField()
    Zhvi_4bedroom = ListField()
    Public = ListField()
    MedianSoldPrice_AllHomes = ListField()
    Zri_AllHomes = ListField()
    Turnover_AllHomes = ListField()
    PctOfHomesIncreasingInValues_AllHomes = ListField()
    MedianPctOfPriceReduction_AllHomes = ListField()
    MedianListingPricePerSqft_AllHomes = ListField()
    MedianSoldPricePerSqft_SingleFamilyResidence = ListField()
    HomesSoldAsForeclosures_Ratio_AllHomes = ListField()
    Zhvi_5BedroomOrMore = ListField()
    Sales = ListField()
    Zhvi_BottomTier = ListField()
    PriceToRentRatio_AllHomes = ListField()
    Zhvi_MiddleTier = ListField()
    Zhvi_Condominum = ListField()
    PctOfListingsWithPriceReductions_AllHomes = ListField()
    SalePriceToListRatio_AllHomes = ListField()
    MedianRentalPrice_AllHomes = ListField()
    Zhvi_1bedroom = ListField()
    MedianSoldPricePerSqft_AllHomes = ListField()
    ZriPerSqft_AllHomes = ListField()
    Zhvi_AllHomes = ListField()
    Zhvi_3bedroom = ListField()
    Zhvi_TopTier = ListField()
    PctOfHomesDecreasingInValues_AllHomes = ListField()

    # time series date fields
    PctTransactionsThatArePreviouslyForeclosuredHomes_AllHomes_dates = ListField()
    UnsoldReos_AllHomes_dates = ListField()
    NumberOfHomesForRent_AllHomes_dates = ListField()
    Zhvi_2bedroom_dates = ListField()
    MedianSoldPricePerSqft_Condominum_dates = ListField()
    MedianListingPrice_AllHomes_dates = ListField()
    Zhvi_SingleFamilyResidence_dates = ListField()
    MedianRentalPricePerSqft_AllHomes_dates = ListField()
    MedianValuePerSqft_AllHomes_dates = ListField()
    Zhvi_4bedroom_dates = ListField()
    Public_dates = ListField()
    MedianSoldPrice_AllHomes_dates = ListField()
    Zri_AllHomes_dates = ListField()
    Turnover_AllHomes_dates = ListField()
    PctOfHomesIncreasingInValues_AllHomes_dates = ListField()
    MedianPctOfPriceReduction_AllHomes_dates = ListField()
    MedianListingPricePerSqft_AllHomes_dates = ListField()
    MedianSoldPricePerSqft_SingleFamilyResidence_dates = ListField()
    HomesSoldAsForeclosures_Ratio_AllHomes_dates = ListField()
    Zhvi_5BedroomOrMore_dates = ListField()
    Sales_dates = ListField()
    Zhvi_BottomTier_dates = ListField()
    PriceToRentRatio_AllHomes_dates = ListField()
    Zhvi_MiddleTier_dates = ListField()
    Zhvi_Condominum_dates = ListField()
    PctOfListingsWithPriceReductions_AllHomes_dates = ListField()
    SalePriceToListRatio_AllHomes_dates = ListField()
    MedianRentalPrice_AllHomes_dates = ListField()
    Zhvi_1bedroom_dates = ListField()
    MedianSoldPricePerSqft_AllHomes_dates = ListField()
    ZriPerSqft_AllHomes_dates = ListField()
    Zhvi_AllHomes_dates = ListField()
    Zhvi_3bedroom_dates = ListField()
    Zhvi_TopTier_dates = ListField()
    PctOfHomesDecreasingInValues_AllHomes_dates = ListField()

print 'exiting props/models'
